### ISSUE TITLE
extend search-replace transformer so that it can read fieldRef

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/kustomize#19]
There could be another attribute in the transformer like this
```
replaceWith:
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configs
    fieldref:
      fieldpath: metadata.labels.release
```
