### ISSUE TITLE
gomplate plugin should accept no data sources

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/kustomize#24]
Sometimes you just want to execute a gomplate function.. currently it crashes unless you do:
```
apiVersion: qlik.com/v1
kind: Gomplate
metadata:
  name: ca-certificate
  labels:
    key: gomplate
dataSource:
  ejson:
    filePath: ""
```

should be able to omit the dataSource section completely
