### ISSUE TITLE
GitImageTag transformer

### ISSUE THREAD

**Issue by andriy-bulynko** [qlik-oss/kustomize#35]
This is the kustomization.yaml  (top level componnent repo build) of the compoent repo. `audit` is just the component manifest in the component repo.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audit
transformers:
  - imagegittag.yaml
```
`imagegittag.yaml` is the transformer. It takes the `audit` manifest (as a resource) and replaces image tags with the latest tag on that branch that corresponds to the HEAD commitid of the repo the transformer is in (pwd). If not found , use default , if default is not specified, do nothing.
```
apiVersion: qlik.com/v1
kind: GitImageTag
metadata:
  name: qseokversion
images:
  - name: qlik-docker-qsefe.bintray.io/audit
    default: latest
```
